### ISSUE TITLE
1.0.1 breaking in Electron

### ISSUE THREAD

**Issue by nucleardreamer** [soldair/node-buffer-indexof#5]
Just incase it matters, im getting an error inside electron with the new 1.0.1 pull yesterday

```
Error: Cannot find module 'chalk'
    at Module._resolveFilename (module.js:440:15)
    at Function.Module._resolveFilename (/usr/local/lib/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/buffer-indexof/index.js:67:13)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
```

**Comment by soldair** [comment]
oh great. thanks for the report 1.0.2 on the way

**Comment by soldair** [comment]
published!
chalk was a dev dependency and it should not have been included in index
